return {
 ["name:Hiragino Sans/B:mode=base;script=latn;language=dflt;#b#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/B:mode=base;script=latn;language=dflt;#b#655362"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/B:mode=node;script=latn;language=dflt;#b#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/B:mode=node;script=latn;language=dflt;#b#655362"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/B:mode=node;script=latn;language=dflt;+tlig;#b#655360"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/B:mode=node;script=latn;language=dflt;+tlig;#b#786432"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/B:mode=node;script=latn;language=dflt;+tlig;#b#943718"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc", 1 },
 ["name:Hiragino Sans/BI:mode=base;script=latn;language=dflt;#bi#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans/BI:mode=node;script=latn;language=dflt;#bi#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans/I:mode=base;script=latn;language=dflt;#i#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans/I:mode=node;script=latn;language=dflt;#i#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;#655358"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;#655362"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;script=latn;language=dflt;#327680"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;script=latn;language=dflt;#458752"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;script=latn;language=dflt;#655360"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;script=latn;language=dflt;#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=base;script=latn;language=dflt;#655362"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;#655358"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;#655362"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;script=latn;language=dflt;#655361"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;script=latn;language=dflt;#655362"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;script=latn;language=dflt;+tlig;#786432"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Hiragino Sans:mode=node;script=latn;language=dflt;+tlig;#943718"]={ "/System/Library/Fonts/ヒラギノ角ゴシック W4.ttc", 1 },
 ["name:Menlo/B:mode=base;language=dflt;#b#655361"]={ "/System/Library/Fonts/Menlo.ttc", 2 },
 ["name:Menlo/B:mode=base;language=dflt;#b#655362"]={ "/System/Library/Fonts/Menlo.ttc", 2 },
 ["name:Menlo/B:mode=node;language=dflt;#b#655361"]={ "/System/Library/Fonts/Menlo.ttc", 2 },
 ["name:Menlo/B:mode=node;language=dflt;#b#655362"]={ "/System/Library/Fonts/Menlo.ttc", 2 },
 ["name:Menlo/BI:mode=base;language=dflt;#bi#655361"]={ "/System/Library/Fonts/Menlo.ttc", 4 },
 ["name:Menlo/BI:mode=base;language=dflt;#bi#655362"]={ "/System/Library/Fonts/Menlo.ttc", 4 },
 ["name:Menlo/BI:mode=node;language=dflt;#bi#655361"]={ "/System/Library/Fonts/Menlo.ttc", 4 },
 ["name:Menlo/BI:mode=node;language=dflt;#bi#655362"]={ "/System/Library/Fonts/Menlo.ttc", 4 },
 ["name:Menlo/I:mode=base;language=dflt;#i#655361"]={ "/System/Library/Fonts/Menlo.ttc", 3 },
 ["name:Menlo/I:mode=base;language=dflt;#i#655362"]={ "/System/Library/Fonts/Menlo.ttc", 3 },
 ["name:Menlo/I:mode=node;language=dflt;#i#655361"]={ "/System/Library/Fonts/Menlo.ttc", 3 },
 ["name:Menlo/I:mode=node;language=dflt;#i#655362"]={ "/System/Library/Fonts/Menlo.ttc", 3 },
 ["name:Menlo:mode=base;#655358"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=base;#655362"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=base;language=dflt;#655361"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=base;language=dflt;#655362"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=node;#655358"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=node;#655362"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=node;language=dflt;#655361"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=node;language=dflt;#655362"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
 ["name:Menlo:mode=node;language=dflt;#659100"]={ "/System/Library/Fonts/Menlo.ttc", 1 },
}